[package]
name = "glass"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
borsh = "0.10.3"
clap = { version = "4.4.16", features = ["derive"] }
dotenv = "0.15.0"
mpl-token-metadata = "4.0.0"
solana-program = "1.17.15"
solana-rpc-client = "1.17.16"
solana-sdk = "1.17.16"
tokio = { version = "1.35.1", features = ["full"] }
spl-associated-token-account = { version = ">= 1.1.3, < 3.0", features = ["no-entrypoint"] }
spl-token = { version = ">= 3.5.0, < 5.0", features = ["no-entrypoint"] }
