[package]
name = "glass"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "glass"
crate-type = ["cdylib", "lib"]

[dependencies]
solana-program = "1.17.15"
